<input type="hidden" name="searchStartDate" id="searchStartDate" value="<c:out value='${searchVO.searchStartDate}'/>"/>
<input type="hidden" name="searchEndDate" id="searchEndDate" value="<c:out value='${searchVO.searchEndDate}'/>"/>
<input type="hidden" name="searchCondition" id="searchCondition" value="<c:out value='${searchVO.searchCondition}'/>"/>
<input type="hidden" name="placeCondition" id="placeCondition" value="<c:out value='${searchVO.placeCondition}'/>"/>
<input type="hidden" name="searchKeyword" id="searchKeyword" value="<c:out value='${searchVO.searchKeyword}'/>"/>
<input type="hidden" name="pageIndex" id="pageIndex" value="<c:out value='${searchVO.pageIndex}'/>"/>

<input type="hidden" name="schEtc01" id="schEtc01" value="<c:out value='${searchVO.schEtc01}'/>"/>
<input type="hidden" name="schEtc02" id="schEtc02" value="<c:out value='${searchVO.schEtc02}'/>"/>
<input type="hidden" name="schEtc03" id="schEtc03" value="<c:out value='${searchVO.schEtc03}'/>"/>
<input type="hidden" name="schEtc04" id="schEtc04" value="<c:out value='${searchVO.schEtc04}'/>"/>
<input type="hidden" name="schEtc05" id="schEtc05" value="<c:out value='${searchVO.schEtc05}'/>"/>
<input type="hidden" name="schEtc06" id="schEtc06" value="<c:out value='${searchVO.schEtc06}'/>"/>
<input type="hidden" name="schEtc07" id="schEtc07" value="<c:out value='${searchVO.schEtc07}'/>"/>
<input type="hidden" name="schEtc08" id="schEtc08" value="<c:out value='${searchVO.schEtc08}'/>"/>
<input type="hidden" name="schEtc09" id="schEtc09" value="<c:out value='${searchVO.schEtc09}'/>"/>
<input type="hidden" name="schEtc10" id="schEtc10" value="<c:out value='${searchVO.schEtc10}'/>"/>
<input type="hidden" name="schEtc13" id="schEtc13" value="<c:out value='${searchVO.schEtc13}'/>"/>
<input type="hidden" name="schEtc14" id="schEtc14" value="<c:out value='${searchVO.schEtc14}'/>"/>
<input type="hidden" name="schEtc15" id="schEtc15" value="<c:out value='${searchVO.schEtc15}'/>"/>
